apiVersion: ${APIVER}

environment: ${ENV}

version: ${VER}

buildID: ${BUILDID}

kind: deployment

manifest:
  - ${JAR_FILE}.jar
  - ${YAML}.yaml
  - dockerfile
  - ${MD5NUM}

deployment:
  type: ${DEPLOY_TYPE}
  target: ${DEPLOY_TARGET}
  style: ${DEPLOY_STYLE}
  window: ${DEPLOY_WINDOW}

#Optional Fields
healthcheckURI: ":80/irmod/test.html"

  
    
        